# Generated by Django 4.0 on 2023-06-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='customer_username',
            field=models.CharField(max_length=200),
        ),
    ]
